[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
evm_version = "paris"

via_ir = true
optimizer = true
optimizer_runs = 200

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
worldchain_sepolia = "${https://worldchain-sepolia.explorer.alchemy.com/}"

[etherscan]
worldchain_sepolia = { key = "ANY_STRING", url = "https://worldchain-sepolia.explorer.alchemy.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options